### ISSUE TITLE
2 misc packages

### ISSUE THREAD

**Issue by cattyngmd** [TheFishDevs/Bloomware#21]
**Describe the bug**
2 misc packages

**Expected behavior**
check code...

**Screenshots**
ok
![image](https://user-images.githubusercontent.com/60744119/129228828-debc55e1-0fcb-4e83-9171-290fd450903a.png)

**Additional context**
lmfao

**Comment by yer7700** [comment]
bebra issue

**Comment by TheAirBlow** [comment]
What's the problem here? It's just two packages

**Comment by cattyngmd** [comment]
> What's the problem here? It's just two packages

bro

**Comment by TheAirBlow** [comment]
> > What's the problem here? It's just two packages
> 
> bro

suka bluat obyasni normal'no

**Comment by DiOnFire** [comment]
fixed
