### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by TheAirBlow** [TheFishDevs/Bloomware#24]
Scheme you are using is very likely to be semantic versioning (https://semver.org), but you don't follow it correctly.

Semver explained:
THEY SHOULD NOT BE ZERO!
X (first number) - Major changes
Y (second number) - Minor changes
Z (third number) - Patches, bugfix

An example are releases. I don't think 11 comes after 1 (this is would be wrong too). First number should be 1 (not zero), then we have 1 (as the previous version), and then set the bugfix number, and we get 1.1.1, that's all.

**Comment by OffeeX** [comment]
Ok.
