### ISSUE TITLE
Pull requests instead of commits

### ISSUE THREAD

**Issue by TheAirBlow** [TheFishDevs/Bloomware#25]
As I see, you use pull requests and merging them instead of commiting directly. This is NOT the right thing to do.

Just do:
Windows: Download git for windows
Linux: Install git package from your PM

If this is already done, skip this.
If your local repo was not cloned, but downloaded from github, please delete it and do git clone.

Then you need to configure git:
```
git config --global user.name <username>
git config --global user.email <email>
```

After that, try to do a test commit and push it.
It will promt you to login. If you use 2-FA auth, then create a token, give it all permissions, copy it, and use it instead of a password.

**Comment by DiOnFire** [comment]
fixed
