### ISSUE TITLE
Discord is broken

### ISSUE THREAD

**Issue by TheAirBlow** [TheFishDevs/Bloomware#30]
**Describe the bug**
When joining Discord, I can't see any channels and the channel that I'm invited to is not visible (permissions issue)

**Expected behavior**
Have channels ofc, common sense

**Screenshots**
![image](https://user-images.githubusercontent.com/68467762/129339314-741ac64e-32e9-4232-8c35-44fe802eb88a.png)

**Comment by DiOnFire** [comment]
bot autorole issue
