### ISSUE TITLE
хуйня 

### ISSUE THREAD

**Issue by 9mq** [TheFishDevs/Bloomware#36]
**Describe the bug**
Describe an issue in general and put more information about it, if you want this to be solved faster.

**Expected behavior**
How you expected this should've worked.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Хуйня

**Comment by ZI7PPER** [comment]
Блять конструктив от этого репозитория так и прёт. Заебали уже, честно.
