### ISSUE TITLE
StorageESP  bug

### ISSUE THREAD

**Issue by RinixGG** [TheFishDevs/Bloomware#43]
**Describe the bug**
Шалкер подсвечивается не по полному хитбоксу(немного режет глаз и странно выглядит)

**Expected behavior**
Чтобы шалкер подсвечивался полностью

**Screenshots**
![IMG_20210823_174153_690.jpg](https://user-images.githubusercontent.com/73175330/130467497-78406dfb-1349-4b85-82aa-b09ca1973d94.jpg)

**Comment by DiOnFire** [comment]
уже пофиксил, жди следующего обновления =)

**Comment by RinixGG** [comment]
> уже пофиксил, жди следующего обновления =)

О, круто

**Comment by DiOnFire** [comment]
1 min fix

**Comment by NightDesertOrig** [comment]
Здесь по поводу новых функций?
