### ISSUE TITLE
чит не видит русскую кириллицу 

### ISSUE THREAD

**Issue by INEDED** [TheFishDevs/Bloomware#44]
![Minecraft_ 1 16 5 - Одиночная игра 23 08 2021 23_49_25](https://user-images.githubusercontent.com/89421834/130517561-f1b17c14-6db2-4dd9-b4bb-f48479b0ef47.png)

**Comment by cattyngmd** [comment]
это метеор

**Comment by DiOnFire** [comment]
no comment.
