### ISSUE TITLE
Little freecam bug

### ISSUE THREAD

**Issue by RinixGG** [TheFishDevs/Bloomware#48]
**Describe the bug**
При попытке залета в толщу блоков из любой полости(блоков воздуха), если перестать жать w, то тебя немного выпихивает и тормозит
**Expected behavior**
Чтобы тебя не выпихивало
**Screenshots**
![2021-09-01_22 31 03](https://user-images.githubusercontent.com/73175330/131732445-096a743f-3814-40f4-8aa7-b9eba7fac679.png)
(видео не получилось закинуть из-за размера файла)

**Comment by ZI7PPER** [comment]
Можешь попробовать кинуть видос в дс блумвейра или в личку диону с упоминанием открытого бага здесь.

**Comment by DiOnFire** [comment]
Пофикшу

**Comment by fuckyouthinkimboogieman** [comment]
mc.player.noClip ГОВНО

**Comment by OffeeX** [comment]
fixed. В некст обнове будет все норм
